services:
  db:
    image: postgres:15-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: g-now
    restart: always
    networks:
      - g-now
networks:
  g-now:
